[package]
org = "ballerinax"
name = "ballerina_fhir_server"
version = "2.0.1"
distribution = "2201.12.10"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "r4"]
template = true

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
artifactId = "h2"
version = "2.3.232"
groupId = "com.h2database"

[[platform.java21.dependency]]
artifactId = "postgresql"
version = "42.7.9"
groupId = "org.postgresql"

# [[dependency]]
# org = "ballerinax"
# name = "health.fhir.r4.international401"
# version = "3.0.1"
# repository="local"

# [[dependency]]
# org = "ballerinax"
# name = "health.fhir.r4utils.fhirpath"
# version = "4.0.0"


